# Generated by Django 4.2.2 on 2023-06-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
    ]
